### ISSUE TITLE
Automatische tests

### ISSUE THREAD

**Issue by pieterjanin** [SELab-2/UGent-5#20]
Wanneer een indiening wordt gemaakt, moeten volgende zaken gebeuren:

```[tasklist]
### Tasks
- [x] Basischecks op bestandsextenties en inhoud van zip-bestanden worden uitgevoerd.
- [x] Automatische tests via testscript worden uitgevoerd in dockercontainer.
- [x] Gegenereerde artifacts worden opgeslagen.
- [x] De uitkomst van deze tests updatet de status van de indiening.
```
