### ISSUE TITLE
Authenticatie via CAS

### ISSUE THREAD

**Issue by reyniersbram** [SELab-2/UGent-5#4]
Om registratie via CAS te kunnen bekomen moeten enkele stappen ondernomen worden. Meer info is [hier](https://helpdesk.ugent.be/webhosting/en/cas.php) te vinden.

- [x] Onze app moet geregistreerd worden, zie #5 
- [ ] De frontend moet de authenticatie ondersteunen, zie #6 
- [ ] De backend moet bijhouden welke gebruiker wanneer ingelogd is, zie #7 
- [ ] Een gebruker moet kunnen uitloggen, zie #10 #11
